#!/usr/bin/node

var Fraction = require('fractional').Fraction;
var colors = require('colors');
var argv = require('yargs')
  .usage('Usage: $0 [options]')
  .default('k', 'C')
  .alias('k', 'key')
  .describe('k', 'Harmonica tonality')
  .default('p', 'scale heptatonic major natural')
  .alias('p', 'progression')
  .describe('p', 'scale or chord progression')
  //.default('t', 'C')
  .alias('t', 'tonality')
  .describe('t', 'Scale tonality')
  .default('o', '1-3')
  .describe('o', 'Octave range between 1 and 3')
  .alias('o', 'octaves')
  .help('h')
  .alias('h', 'help')
  .epilog('author: IceOnFire')
  .argv;

var notes = [ ' C', ' Db',  ' D', ' Eb',  ' E', ' F',  ' Gb',  ' G', ' Ab',   ' A',  ' Bb',   ' B' ];

var holes = [ ' 1', '-1\'', '-1', ' X',   ' 2', '-2"', '-2\'', '-2', '-3"\'', '-3"', '-3\'',  '-3',
              ' 4', '-4\'', '-4', ' 4\'', ' 5', '-5',  ' 5\'', ' 6', '-6\'',  '-6',  ' 6\'',  '-7',
              ' 7', '-7\'', '-8', ' 8\'', ' 8', '-9',  ' 9\'', ' 9', ' X',    '-10', '-10\'', ' 10\'',
              ' 10' ];

var progressions = {
  scale : {
    pentatonic : {
      minor : [ 0, 3, 5, 7, 10 ],
      major : [ 0, 2, 4, 7, 9 ]
    },
    hexatonic : {
      blues : [ 0, 3, 5, 6, 7, 10 ] // derived from minor
    },
    heptatonic : {
      diatonic : {
        ionian :     [ 0, 2, 4, 5, 7, 9, 11 ],
        dorian :     [ 0, 2, 3, 5, 7, 9, 10 ],
        phrygian :   [ 0, 1, 3, 5, 7, 8, 10 ],
        lydian :     [ 0, 2, 4, 6, 7, 9, 11 ],
        mixolydian : [ 0, 2, 4, 5, 7, 9, 10 ],
        aeolian :    [ 0, 2, 3, 5, 7, 8, 10 ],
        locrian :    [ 0, 1, 3, 5, 6, 8, 10 ]
      },
      minor : {
        natural :  [ 0, 2, 3, 5, 7, 8, 10 ], // aeolian
        harmonic : [ 0, 2, 3, 5, 7, 8, 11 ],
        melodic : {
          ascending :  [ 0, 2, 3, 5, 7, 9, 11 ],
          descending : [ 0, 2, 3, 5, 7, 8, 10 ] // aeolian
        }
      },
      major : {
        natural : [ 0, 2, 4, 5, 7, 9, 11 ], // ionian
      },
      blues : [ 0, 3, 5, 6, 7, 10, 11 ] // one more note
    },
  },
  chord : {
    major : [ 0, 4, 7 ],
    maj7 : [ 0, 4, 7, 11 ],
    maj9 : [ 0, 4, 7, 11, 13 ],
    maj11 : [ 0, 4, 7, 11, 13, 15 ],
    maj13 : [ 0, 4, 7, 11, 13, 15, 17 ],
    6 : [ 0, 4, 7, 10 ],
    add9 : [ 0, 4, 7, 13 ]
  }
};

var tonalities = {
  'C' : 0,
  'C#' : 1, 'Db' : 1,
  'D' : 2,
  'D#' : 3, 'Eb' : 3,
  'E' : 4,
  'F' : 5,
  'F#' : 6, 'Gb' : 6,
  'G' : 7,
  'G#' : 8, 'Ab' : 8,
  'A' : 9,
  'A#' : 10, 'Bb' : 10,
  'B' : 11
}

var degrees = [ 'tonic', 'supertonic', 'mediant', 'subdominant', 'dominant', 'submediant', 'leading' ];

var getSteps = function(progression, octave, octaves) {
  var o, semitone, theSteps = [];
  for (o = octave; o < octaves; o += 1) {
    for (semitone = 0; semitone < progression.length - 1; semitone += 1) {
      theSteps.push((progression[semitone + 1] - progression[semitone]) / 2);
    }
    theSteps.push((progression[0] + 12 - progression[progression.length - 1]) / 2);
  }
  return theSteps;
}

var getNotes = function(progression, tonality, octave, octaves) {
  var o, semitone, theNotes = [];
  for (o = octave; o < octaves; o += 1) {
    for (semitone = 0; semitone < progression.length; semitone += 1) {
      theNotes.push(notes[(progression[semitone] + tonalities[tonality]) % 12] || ' X');
    }
  }
  theNotes.push(notes[(progression[0] + tonalities[tonality]) % 12] || ' X');
  return theNotes;
}

var getHoles = function(harpkey, progression, tonality, octave, octaves) {
  var o, semitone, theHoles = [];
  for (o = octave; o < octaves; o += 1) {
    for (semitone = 0; semitone < progression.length; semitone += 1) {
      theHoles.push(holes[progression[semitone] + tonalities[tonality] - tonalities[harpkey] + 12 * o] || ' X');
    }
  }
  theHoles.push(holes[progression[0] + tonalities[tonality] - tonalities[harpkey] + 12 * octaves] || ' X');
  return theHoles;
}

var harpkey = argv.k;
var progression = argv.p;
var tonality = argv.t || harpkey;
var octaves = argv.o;

var tokens = progression.split(' ');
progression = progressions;
for (var i = 0; i < tokens.length; i += 1) {
  progression = progression[tokens[i]];
}

tokens = octaves.split('-');
var octave = tokens[0];
octave -= 1;
octaves = tokens[1];

var theSteps = getSteps(progression, octave, octaves);
for (var i = 0; i< theSteps.length; i += 1) {
  var theStep = theSteps[i];
  if (theStep % 1 === 0) {
    theStep = '     ' + theStep;
  } else {
    theStep = '    ' + new Fraction(theStep).toString();
  }
  process.stdout.write(theStep + '\t');
}
process.stdout.write('\n');

var theNotes = getNotes(progression, tonality, octave, octaves);
for (var i = 0; i < theNotes.length; i += 1) {
  var theNote = theNotes[i];
  if (i % progression.length === 0) { // tonic
    theNote = colors.green.bold(theNote);
  } else if ((i % progression.length) % 4 === 0) { // dominant
    theNote = colors.blue.bold(theNote);
  } else if ((i % progression.length) % 6 === 0) { // leading
    theNote = colors.magenta.bold(theNote);
  }
  process.stdout.write(theNote + '\t');
}
process.stdout.write('\n');

var theHoles = getHoles(harpkey, progression, tonality, octave, octaves);
for (var i = 0; i < theHoles.length; i += 1) {
  var theHole = theHoles[i];
  if (i % progression.length === 0) { // tonic
    theHole = colors.green.bold(theHole);
  } else if ((i % progression.length) % 4 === 0) { // dominant
    theHole = colors.blue.bold(theHole);
  } else if ((i % progression.length) % 6 === 0) { // leading
    theHole = colors.magenta.bold(theHole);
  }
  process.stdout.write(theHole + '\t');
}
process.stdout.write('\n');
